name: flutter_lab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리 (Riverpod 2.0 + Generator)
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # 네트워크 통신
  dio: ^5.9.0  # 강력한 HTTP 클라이언트

  # 라우팅
  go_router: ^17.0.1 # 최신 라우팅 솔루션

  # 데이터 모델링 (Freezed: DDD의 Entity와 DTO를 깔끔하게 만들어 줌)
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.6.2
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.2.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # [핵심] 최신 5.0.0/6.0.0 대신 안정적인 4.0.0 사용
  flutter_lints: ^4.0.0

  # [핵심] analyzer 7.x 사태가 일어나기 전의 안정적인 버전들입니다.
  build_runner: 2.4.9
  riverpod_generator: 2.4.0
  riverpod_lint: 2.3.10
  custom_lint: 0.6.4

  # freezed 등을 쓰신다면 아래 버전 추천
  freezed: 2.5.2
  json_serializable: 6.8.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
